
services:
  system_admin:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/system_admin:1.0.2
    container_name: system_admin
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./system.yaml:/etc/system.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 