
services:
  friend_admin:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/friend_admin:1.0.2
    container_name: friend_admin
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./friend.yaml:/etc/friend.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 