
services:
  file_admin:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/file_admin:1.0.2
    container_name: file_admin
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./file.yaml:/etc/file.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 