Name: file
Host: 0.0.0.0
Port: 40600

# MySQL 配置
Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/beaver?charset=utf8mb4&parseTime=True&loc=Local
# Redis 配置
Redis:
  Addr: 127.0.0.1:6379
  Password: '123456'
  DB: 0
# Etcd 配置
Etcd: 127.0.0.1:2379
FileMaxSize:
  image: 2    
  video: 10   
  audio: 2    
  archive: 2  
  document: 2 
  unknown: 10
FileSize: 5 # MB
MaxBytes: 5368709120 # 5GB
UploadDir: uploads
Timeout: 60000
Qiniu: 
  AK: 380CCZeJZztGl2g3mX-OhufNPkkYaE-HqL2ybfvc
  SK: CSaNAQG2hiDUHSpQNJWJmktCA9mj9M2_0qYkRqLr
  Bucket: beaver-im
  Domain: 'http://static.wsrh8888.com'
  ExpireTime: 3600 # 签名URL有效期, 单位：秒
WhiteList:
  - png
  - jpg
  - jpeg
  - gif
  - webp
  - mp4
  - apk
BlackList:
  - exe
  - sh
  - bat