
services:
  emoji_api:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/emoji_api:1.0.2
    container_name: emoji_api
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./emoji.yaml:/etc/emoji.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 
