
services:
  chat_admin:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/chat_admin:1.0.2
    container_name: chat_admin
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./chat.yaml:/etc/chat.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 