
services:
  feedback_admin:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/feedback_admin:1.0.2
    container_name: feedback_admin
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./feedback.yaml:/etc/feedback.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 