
services:
  auth_admin:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/auth_admin:1.0.2
    container_name: auth_admin
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./auth.yaml:/etc/auth.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 