
services:
  moment_admin:
    image: registry.cn-hangzhou.aliyuncs.com/beaver_im/moment_admin:1.0.2
    container_name: moment_admin
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./moment.yaml:/etc/moment.yaml:ro
    deploy:
      restart_policy:
        condition: any
    pull_policy: always 